esphome:
  name: hall-dining-lights

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.0.208
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hall-Dining-Lights"
    password: "password"

captive_portal:

switch:
  - platform: gpio
    name: "Dining Corner Light"
    pin: D0
    id: switch0
  
  - platform: gpio
    name: "Dining Warm Light"
    pin: D5
    id: switch1
  
  
  - platform: gpio
    name: "Dining White Light"
    pin: D8
    id: switch2

  - platform: gpio
    name: "Balcony Light"
    pin: D3
    id: switch3
  
binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    name: "Dining Corner Light Button"
    on_press:
      then:
        - switch.toggle: switch0
    filters:
    - delayed_on: 100ms
    
  - platform: gpio
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    name: "Dining Warm Light Button"
    on_press:
      then:
        - switch.toggle: switch1
    filters:
    - delayed_on: 50ms
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
    name: "Dining White Light Button"
    on_press:
      then:
        - switch.toggle: switch2
    filters:
    - delayed_on: 50ms
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
    name: "Balcony Light Button"
    on_press:
      then:
        - switch.toggle: switch3
    filters:
    - delayed_on: 50ms